### ISSUE TITLE
Getting started page: Product instead of Picture

### ISSUE THREAD

**Issue by Spoke2k** [sangria-graphql/sangria-website#43]
Hi, I'm currently reading through the getting started page and I'm a little bit confused about two occurrences of `Product`where I think `Picture` would be correct.

They can both be found at: http://sangria-graphql.org/getting-started/#picture-type

>  In this simple example we just use the context value (which would be of type Product)

> Let’s simplify the GraphQL object type definition for Product with deriveObjectType macro

Hopefully I'm not bothering you with something I misinterpreted.

**Comment by OlegIlyenko** [comment]
Ooops.... you are absolutely right. It should be `Picture` :) Would you like to make a PR?

https://github.com/sangria-graphql/sangria-website/edit/master/getting-started.md

**Comment by Spoke2k** [comment]
I created #44 👍

**Comment by OlegIlyenko** [comment]
Fixed in #44
